/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javadakon;

import java.awt.Label;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author adan
 */
public class GamePlay extends javax.swing.JFrame {
    private String ip, port;
    boolean menangSuit;
    int boardArr[]={0,7,7,7,7,7,7,7,0,7,7,7,7,7,7,7};

    /**
     * Creates new form Dakon
     *
     * @param ip
     * @param port
     * @param menangSuit
     */
    public GamePlay(String ip, String port, boolean menangSuit) {
        initComponents();
        hijau0.setVisible(false);
        hijau1.setVisible(false);
        hijau2.setVisible(false);
        hijau3.setVisible(false);
        hijau4.setVisible(false);
        hijau5.setVisible(false);
        hijau5.setVisible(false);
        hijau6.setVisible(false);
        hijau7.setVisible(false);
        hijau8.setVisible(false);
        hijau9.setVisible(false);
        hijau10.setVisible(false);
        hijau11.setVisible(false);
        hijau12.setVisible(false);
        hijau13.setVisible(false);
        hijau14.setVisible(false);
        hijau15.setVisible(false);
        
        this.ip = ip;
        this.port = port;
        this.menangSuit = menangSuit;
        
        System.out.println("ip: " + ip + ", port: " + port + ", menang suit: " + menangSuit);
    }

    int tampung = 0;
    Timer tm = new Timer(100, new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
            read();
//            tampung++;
//            if (tampung == 3) {
//                tm.stop();
//            }

        }
    });

    private GamePlay() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextArea();
        hijau9 = new javax.swing.JLabel();
        hijau10 = new javax.swing.JLabel();
        hijau11 = new javax.swing.JLabel();
        hijau12 = new javax.swing.JLabel();
        hijau13 = new javax.swing.JLabel();
        hijau14 = new javax.swing.JLabel();
        hijau15 = new javax.swing.JLabel();
        hijau7 = new javax.swing.JLabel();
        hijau6 = new javax.swing.JLabel();
        hijau5 = new javax.swing.JLabel();
        hijau4 = new javax.swing.JLabel();
        hijau3 = new javax.swing.JLabel();
        hijau2 = new javax.swing.JLabel();
        hijau1 = new javax.swing.JLabel();
        hijau8 = new javax.swing.JLabel();
        hijau0 = new javax.swing.JLabel();
        txtJml0 = new javax.swing.JLabel();
        txtJml1 = new javax.swing.JLabel();
        txtJml2 = new javax.swing.JLabel();
        txtJml3 = new javax.swing.JLabel();
        txtJml4 = new javax.swing.JLabel();
        txtJml5 = new javax.swing.JLabel();
        txtJml6 = new javax.swing.JLabel();
        txtJml7 = new javax.swing.JLabel();
        txtJml8 = new javax.swing.JLabel();
        txtJml9 = new javax.swing.JLabel();
        txtJml10 = new javax.swing.JLabel();
        txtJml11 = new javax.swing.JLabel();
        txtJml12 = new javax.swing.JLabel();
        txtJml13 = new javax.swing.JLabel();
        txtJml14 = new javax.swing.JLabel();
        txtJml15 = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        lblPlayer1 = new javax.swing.JLabel();
        lblScore2 = new javax.swing.JLabel();
        lblScore1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/merahBesar.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(240, 560, 73, 23);
        getContentPane().add(txtInput);
        txtInput.setBounds(30, 580, 174, 20);

        txtChat.setEditable(false);
        txtChat.setColumns(20);
        txtChat.setRows(5);
        jScrollPane1.setViewportView(txtChat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 470, 166, 96);

        hijau9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau9);
        hijau9.setBounds(730, 320, 90, 110);

        hijau10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau10);
        hijau10.setBounds(640, 320, 90, 110);

        hijau11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau11);
        hijau11.setBounds(550, 320, 90, 110);

        hijau12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau12);
        hijau12.setBounds(450, 320, 90, 110);

        hijau13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau13);
        hijau13.setBounds(360, 320, 90, 110);

        hijau14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau14);
        hijau14.setBounds(270, 320, 90, 110);

        hijau15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau15);
        hijau15.setBounds(170, 320, 90, 110);

        hijau7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau7);
        hijau7.setBounds(730, 190, 90, 110);

        hijau6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau6);
        hijau6.setBounds(640, 190, 90, 110);

        hijau5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau5);
        hijau5.setBounds(550, 190, 90, 110);

        hijau4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau4);
        hijau4.setBounds(450, 190, 90, 110);

        hijau3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau3);
        hijau3.setBounds(360, 190, 90, 110);

        hijau2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau2);
        hijau2.setBounds(270, 190, 90, 110);

        hijau1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijau.png"))); // NOI18N
        getContentPane().add(hijau1);
        hijau1.setBounds(170, 190, 90, 110);

        hijau8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hijau8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijauBesar.png"))); // NOI18N
        getContentPane().add(hijau8);
        hijau8.setBounds(820, 250, 120, 120);

        hijau0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hijau0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hijauBesar.png"))); // NOI18N
        getContentPane().add(hijau0);
        hijau0.setBounds(50, 250, 120, 120);

        txtJml0.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml0.setForeground(new java.awt.Color(255, 255, 255));
        txtJml0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml0.setText("0");
        getContentPane().add(txtJml0);
        txtJml0.setBounds(70, 300, 80, 30);

        txtJml1.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml1.setForeground(new java.awt.Color(255, 255, 255));
        txtJml1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml1.setText("0");
        getContentPane().add(txtJml1);
        txtJml1.setBounds(185, 230, 50, 30);

        txtJml2.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml2.setForeground(new java.awt.Color(255, 255, 255));
        txtJml2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml2.setText("0");
        getContentPane().add(txtJml2);
        txtJml2.setBounds(285, 230, 50, 30);

        txtJml3.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml3.setForeground(new java.awt.Color(255, 255, 255));
        txtJml3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml3.setText("0");
        getContentPane().add(txtJml3);
        txtJml3.setBounds(375, 230, 50, 30);

        txtJml4.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml4.setForeground(new java.awt.Color(255, 255, 255));
        txtJml4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml4.setText("0");
        getContentPane().add(txtJml4);
        txtJml4.setBounds(465, 230, 50, 30);

        txtJml5.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml5.setForeground(new java.awt.Color(255, 255, 255));
        txtJml5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml5.setText("0");
        getContentPane().add(txtJml5);
        txtJml5.setBounds(565, 230, 50, 30);

        txtJml6.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml6.setForeground(new java.awt.Color(255, 255, 255));
        txtJml6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml6.setText("0");
        getContentPane().add(txtJml6);
        txtJml6.setBounds(655, 230, 50, 30);

        txtJml7.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml7.setForeground(new java.awt.Color(255, 255, 255));
        txtJml7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml7.setText("0");
        getContentPane().add(txtJml7);
        txtJml7.setBounds(745, 230, 50, 30);

        txtJml8.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml8.setForeground(new java.awt.Color(255, 255, 255));
        txtJml8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml8.setText("0");
        getContentPane().add(txtJml8);
        txtJml8.setBounds(835, 300, 90, 30);

        txtJml9.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml9.setForeground(new java.awt.Color(255, 255, 255));
        txtJml9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml9.setText("0");
        getContentPane().add(txtJml9);
        txtJml9.setBounds(740, 360, 60, 30);

        txtJml10.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml10.setForeground(new java.awt.Color(255, 255, 255));
        txtJml10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml10.setText("0");
        getContentPane().add(txtJml10);
        txtJml10.setBounds(650, 360, 60, 30);

        txtJml11.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml11.setForeground(new java.awt.Color(255, 255, 255));
        txtJml11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml11.setText("0");
        getContentPane().add(txtJml11);
        txtJml11.setBounds(560, 360, 60, 30);

        txtJml12.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml12.setForeground(new java.awt.Color(255, 255, 255));
        txtJml12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml12.setText("0");
        getContentPane().add(txtJml12);
        txtJml12.setBounds(460, 360, 60, 30);

        txtJml13.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml13.setForeground(new java.awt.Color(255, 255, 255));
        txtJml13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml13.setText("0");
        getContentPane().add(txtJml13);
        txtJml13.setBounds(370, 360, 60, 30);

        txtJml14.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml14.setForeground(new java.awt.Color(255, 255, 255));
        txtJml14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml14.setText("0");
        getContentPane().add(txtJml14);
        txtJml14.setBounds(280, 360, 60, 30);

        txtJml15.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtJml15.setForeground(new java.awt.Color(255, 255, 255));
        txtJml15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJml15.setText("0");
        getContentPane().add(txtJml15);
        txtJml15.setBounds(180, 360, 60, 30);

        lblPlayer2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblPlayer2.setForeground(java.awt.Color.white);
        lblPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer2.setText("Player 2");
        getContentPane().add(lblPlayer2);
        lblPlayer2.setBounds(690, 20, 210, 60);

        lblPlayer1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblPlayer1.setForeground(java.awt.Color.white);
        lblPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer1.setText("Player 1");
        getContentPane().add(lblPlayer1);
        lblPlayer1.setBounds(90, 20, 210, 60);

        lblScore2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblScore2.setForeground(new java.awt.Color(255, 255, 255));
        lblScore2.setText("0");
        getContentPane().add(lblScore2);
        lblScore2.setBounds(540, 30, 21, 40);

        lblScore1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblScore1.setForeground(new java.awt.Color(255, 255, 255));
        lblScore1.setText("0");
        getContentPane().add(lblScore1);
        lblScore1.setBounds(440, 30, 21, 40);

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 20, 200, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/player1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 300, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/player2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 10, 300, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skor.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 10, 200, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dakon.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 180, 950, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -6, 990, 640);

        setSize(new java.awt.Dimension(1000, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String tempChat = txtChat.getText();
        String text = txtInput.getText();
        int portInt = Integer.parseInt(port);
        try {
            Socket cl = new Socket(ip, portInt);
            DataOutputStream dos = new DataOutputStream(cl.getOutputStream());
            dos.writeBytes(text);

            cl.close();
            dos.close();

            txtChat.setText(tempChat + "\n" + text);

            tm.start();
        } catch (Exception e) {
            System.out.println("gagal");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (menangSuit) {
            // jika menang suit
            hijau1.setVisible(true);
            hijau2.setVisible(true);
            hijau3.setVisible(true);
            hijau4.setVisible(true);
            hijau5.setVisible(true);
            hijau6.setVisible(true);
            hijau7.setVisible(true);
        } else {
            // jika kalah
            tm.start();
        }
    }//GEN-LAST:event_formWindowOpened

    public void read() {
        String tempChat = txtChat.getText();
        int portInt = Integer.parseInt(port);

        try {
            ServerSocket ss = new ServerSocket(portInt);
            Socket sk = ss.accept();
            BufferedReader br = new BufferedReader(
                    new InputStreamReader(sk.getInputStream())
            );
            String line = br.readLine();

            txtChat.setText(tempChat + "\n" + line);

            if (line.equals(null)) {
                System.out.println("null");
            } else {
                tm.stop();
            }
            System.out.println(line);

            sk.close();
            ss.close();
        } catch (Exception err) {
            System.out.println(err);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new GamePlay().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hijau0;
    private javax.swing.JLabel hijau1;
    private javax.swing.JLabel hijau10;
    private javax.swing.JLabel hijau11;
    private javax.swing.JLabel hijau12;
    private javax.swing.JLabel hijau13;
    private javax.swing.JLabel hijau14;
    private javax.swing.JLabel hijau15;
    private javax.swing.JLabel hijau2;
    private javax.swing.JLabel hijau3;
    private javax.swing.JLabel hijau4;
    private javax.swing.JLabel hijau5;
    private javax.swing.JLabel hijau6;
    private javax.swing.JLabel hijau7;
    private javax.swing.JLabel hijau8;
    private javax.swing.JLabel hijau9;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblScore1;
    private javax.swing.JLabel lblScore2;
    private javax.swing.JTextArea txtChat;
    private javax.swing.JTextField txtInput;
    private javax.swing.JLabel txtJml0;
    private javax.swing.JLabel txtJml1;
    private javax.swing.JLabel txtJml10;
    private javax.swing.JLabel txtJml11;
    private javax.swing.JLabel txtJml12;
    private javax.swing.JLabel txtJml13;
    private javax.swing.JLabel txtJml14;
    private javax.swing.JLabel txtJml15;
    private javax.swing.JLabel txtJml2;
    private javax.swing.JLabel txtJml3;
    private javax.swing.JLabel txtJml4;
    private javax.swing.JLabel txtJml5;
    private javax.swing.JLabel txtJml6;
    private javax.swing.JLabel txtJml7;
    private javax.swing.JLabel txtJml8;
    private javax.swing.JLabel txtJml9;
    // End of variables declaration//GEN-END:variables
}
